---
title: "Pratica em R - graficos, visualização e dashboards"

---

```{r}
#Instalação e carregamento de pacotes:
import 
install.packages("RColorBrewer")
library("RColorBrewer")
```


```{r}
#Leitura dos dados
dados = read.csv('dados.csv', sep=";")
head(dados)
```


```{r}
#Sumário estatístico
summary(dados$VALOREMPENHO)
summary(dados$PIB)
```


```{r warning=FALSE}
#Alguns gráficos
par(mfrow=c(1, 1), cex.main=1.2, cex.lab=1.2, cex.axis=1.2, cex.sub=1.2)

boxplot(dados$VALOREMPENHO, main="Valores de Empenho", col = brewer.pal(n = 3, name = "Paired"), outline = F )
boxplot(dados$PIB ,main="Valores de PIB", col = brewer.pal(n = 3, name = "Pastel1"), outline = F )
hist(dados$VALOREMPENHO, main="Valores de Empenho", col = brewer.pal(n = 3, name = "Paired"))
hist(dados$PIB, main="Valores de PIB", col = brewer.pal(n = 3, name = "Pastel1"), outline = F )

par(mfrow=c(1, 1))  # Restaurar layout padrão
```


```{r}
#maiores empenhos
Mempenho = head(dados[order(-dados$VALOREMPENHO),],10)
barplot(Mempenho$VALOREMPENHO, col=brewer.pal(n = 10, name = "Paired"),las=2,main = "Maiores Empenhos")
legend("topright",legend=Mempenho$MUNICIPIO,col = brewer.pal(n = 10, name = "Paired"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()
```


```{r}
#Maiores Pibs
Mpibs =   head(dados[order(-dados$PIB),],10)
barplot(Mpibs$PIB, col=rainbow(10), las=2, main="Maiores PIBs",
        names.arg=Mpibs$MUNICIPIO, cex.names=0.7)
legend("topright",legend=Mempenho$MUNICIPIO,col = brewer.pal(n = 10, name = "Spectral"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()
```


```{r}
#Relação entre PIB e empenho
dados$PROPORCAO =   dados$VALOREMPENHO  / dados$PIB 
Mprop = head(dados[order(-dados$PROPORCAO),],10)
barplot(Mprop$PROPORCAO,col=brewer.pal(n = 10, name = "RdBu"),las=2,main = "Maiores Gastos em Proporção ao PIB")
legend("topright",legend=Mprop$MUNICIPIO,col = brewer.pal(n = 10, name = "RdBu"), lty=1:2, cex=0.8, ncol = 2,lwd=4)
box()

```
